### ISSUE TITLE
Add unit tests for helpers.cs

### ISSUE THREAD

**Issue by trangntt-016** [mkim219/kimchi-ssg#25]
Hi @mkim219 ,

I would like to add a couple of unit tests for `ConvertStrToFile()` and `IWrapper`in your project
* [x]  shouldReturnTableOfContentString()
* [x] shouldReturnOptions()
* [x] shouldReturnAVersion()
* [x] shouldThrowExceptionWhenTitleIsEmpty()

**Comment by mkim219** [comment]
Hi @trangntt-016, I will merge after I have a few more test on my Formatter and Linter in CI. Your test is okay :)
