### ISSUE TITLE
Use Path class to work with paths instead of using string operations

### ISSUE THREAD

**Issue by humphd** [mkim219/kimchi-ssg#7]
In various places (e.g., https://github.com/mkim219/kimchi-ssg/blob/main/kimchi-ssg/helpers.cs#L107) you are working with pathnames as regular strings. A better option is to use the [Path](https://docs.microsoft.com/en-us/dotnet/api/system.io.path?view=net-5.0) class, which provides methods for creating and inspecting paths.  This is important when you move between operating systems, where paths are different.

**Comment by mkim219** [comment]
I have fixed issue #7. Thank you David
